### ISSUE TITLE
Chekcpoint : checkpoint/Adult Error Loading Dataset !!

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [mahmoodm2/tableGAN#4]
```
{'id': 'OI_11_00', 'alpha': 1.0, 'beta': 1.0, 'delta_v': 0.0, 'delta_m': 0.0}
{'alpha': <absl.flags._flag.Flag object at 0x7f53f7a55a90>,
 'attrib_num': <absl.flags._flag.Flag object at 0x7f53f7a55e80>,
 'batch_size': <absl.flags._flag.Flag object at 0x7f53f85ba9b0>,
 'beta': <absl.flags._flag.Flag object at 0x7f53f7a55b38>,
 'beta1': <absl.flags._flag.Flag object at 0x7f5402c9fb00>,
 'checkpoint_dir': <absl.flags._flag.Flag object at 0x7f53f7a557f0>,
 'checkpoint_par_dir': <absl.flags._flag.Flag object at 0x7f53f7a55780>,
 'crop': <absl.flags._flag.BooleanFlag object at 0x7f53f7a55978>,
 'dataset': <absl.flags._flag.Flag object at 0x7f53f7a55710>,
 'delta_m': <absl.flags._flag.Flag object at 0x7f53f7a55be0>,
 'delta_v': <absl.flags._flag.Flag object at 0x7f53f7a55c88>,
 'epoch': <absl.flags._flag.Flag object at 0x7f5402d199b0>,
 'feature_size': <absl.flags._flag.Flag object at 0x7f53f7a55f28>,
 'generate_data': <absl.flags._flag.BooleanFlag object at 0x7f53f7a559e8>,
 'h': <tensorflow.python.platform.app._HelpFlag object at 0x7f53f75890b8>,
 'help': <tensorflow.python.platform.app._HelpFlag object at 0x7f53f75890b8>,
 'helpfull': <tensorflow.python.platform.app._HelpfullFlag object at 0x7f53f7589160>,
 'helpshort': <tensorflow.python.platform.app._HelpshortFlag object at 0x7f53f75891d0>,
 'input_height': <absl.flags._flag.Flag object at 0x7f53f9e5c208>,
 'input_width': <absl.flags._flag.Flag object at 0x7f53f7a55320>,
 'label_col': <absl.flags._flag.Flag object at 0x7f53f7a55dd8>,
 'learning_rate': <absl.flags._flag.Flag object at 0x7f5402d19dd8>,
 'output_height': <absl.flags._flag.Flag object at 0x7f53f7a555f8>,
 'output_width': <absl.flags._flag.Flag object at 0x7f53f7a556a0>,
 'sample_dir': <absl.flags._flag.Flag object at 0x7f53f7a55898>,
 'shadow_gan': <absl.flags._flag.BooleanFlag object at 0x7f53f7a55f60>,
 'shgan_input_type': <absl.flags._flag.Flag object at 0x7f53f7589080>,
 'test_id': <absl.flags._flag.Flag object at 0x7f53f7a55d30>,
 'train': <absl.flags._flag.BooleanFlag object at 0x7f53f7a558d0>,
 'train_size': <absl.flags._flag.Flag object at 0x7f53f8bd0320>}
Chekcpoint : checkpoint/Adult
Error Loading Dataset !!

```
Why you said that the `checkpoint files` are automatically generated?

**Comment by Baukebrenninkmeijer** [comment]
I'm not sure what you mean. The checkpoints are generated automatically. However, there seems to be an error loading your dataset. Make sure you have a comma seperated data and label file called `Adult.csv` and `Adults_labels.csv`.

**Comment by soft-nougat** [comment]
Hey Bauke!

Hope you are well and thanks for this repo. :)

I am getting the same issue, the checkpoint won't generate due to an error in loading the dataset. I have downloaded the repo and can confirm I have the following CSVs in \data\Adult - train_Adult_cleaned and train_Adult_labeled.

Any insight would be greatly appreciated. 

Thanks!
Tia

**Comment by Baukebrenninkmeijer** [comment]
Yeah, the repo as it is is broken AF. The file need to be named `Adult.csv` and `Adult_labeled.csv`. I think it should work then.

**Comment by soft-nougat** [comment]
Thanks! Getting the same issue after rename. If anything else comes to mind please post. :)

**Comment by Baukebrenninkmeijer** [comment]
Hey, I just did a pull request with a lot of fixes. I advise you to check it out. I've taken the Ticket dataset as example instead of adult, so use when trying stuff out. Of that I'm sure it works. Hope that helps!

**Comment by Baukebrenninkmeijer** [comment]
I had to rewrite it from what i'm using, so I found another few bugs, but it should be smooth sailing now!

**Comment by mahmoodm2** [comment]
Hi @soft-nougat, based on recent modifications ( thanks Bauke) in function model.py -> load_tabular_data() 
```
This format strings need  Python 3.6+
self.train_data_path = f'data/{dataset_name}/{dataset_name}'
self.train_label_path = f'data/{dataset_name}/{dataset_name}_labels'
```
the original data files for Adult data set needs to be **Adult.csv** and **Adult_labels.csv**. Currently, files in  /data/Adult are "train_Adult_cleaned.csv" and "train_Adult_labels.csv" which should temporary be renamed as:
/data/Adult/train_Adult_cleaned.csv --> Adult.csv
/data/Adult/train_Adult_labels.csv  --> Adult_labels.csv
But the correct names are train_Adult_cleaned.csv and train_Adult_labels as we would have test data sets and not cleaned(raw) data as well.
Hope this can help.

I will fix this and add some visualizations codes (CDF : Cumulative distribution function) we used in the paper as well.

**Comment by TrinhDinhPhuc** [comment]
After renaming the dataset it worked. But I got an issue:
`ValueError: could not convert string to float: '50,2,83311,1,13,1,5,3,1,2,0,0,13,1'`
Here is the log file:
`  File "main.py", line 152, in main
    test_id=FLAGS.test_id
  File "/media/harry/harry/tableGAN/model.py", line 106, in __init__
    self.data_X, self.data_y, self.data_y_normal = self.load_dataset(is_shadow_gan)
  File "/media/harry/harry/tableGAN/model.py", line 809, in load_dataset
    return self.load_tabular_data(self.dataset_name, self.input_height, self.y_dim, self.test_id, load_fake_data)
  File "/media/harry/harry/tableGAN/model.py", line 852, in load_tabular_data
    X = pd.DataFrame(min_max_scaler.fit_transform(X))`

**Comment by soft-nougat** [comment]
Hey guys!

Thanks for all the fixes, but I am getting the same issue as Trinh with Adult dataset. With the Ticket ds, I am getting this:

Traceback (most recent call last):
File "main.py", line 179, in <module>
tf.app.run()
File "C:\Anaconda\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run _sys.exit(main(argv))
File "main.py", line 158, in main
tablegan.train(FLAGS)
TypeError: train() missing 1 required positional argument: 'experiment'

Any ideas as to why this might be?

**Comment by Baukebrenninkmeijer** [comment]
@soft-nougat Ah yes, sorry. Another remnant of my old code. I use comet_ml for experiment tracking and can recommend it. My fork is now updated to reflect the removal of this code and should not give the error anymore.

**Comment by Baukebrenninkmeijer** [comment]
@TrinhDinhPhuc Yeah, my data load function expects the seperator to be a semicolon instead of comma. If you change the seperator to a semicolon or change the function to expect a colon it should work fine. More specifically, change line 816 in model.py to
```
            X = pd.read_csv(self.train_data_path + ".csv", sep=',')
```

**Comment by Baukebrenninkmeijer** [comment]
To both, just clone my fork instead of this repo as I wont keep submitting merge requests since they often don't get accepted in a reasonable time.

**Comment by soft-nougat** [comment]
Perfect Bauke!

It worked for train, checkpoints are there.

Now an issue arises in the generate step, using Adult data.
Error here:

 File "main.py", line 171, in main
    generate_data(sess, tablegan, FLAGS, OPTION)
  File "C:\Users\Tia\Desktop\tableGAN\tableGAN-3a236522dce5a31bb90876b138390080b9d5d441\utils.py", line 416, in generate_data
    min_max_scaler.fit(origin_data)
  File "C:\Anaconda\lib\site-packages\sklearn\preprocessing\data.py", line 308, in fit
    return self.partial_fit(X, y)
  File "C:\Anaconda\lib\site-packages\sklearn\preprocessing\data.py", line 334, in partial_fit
    estimator=self, dtype=FLOAT_DTYPES)
  File "C:\Anaconda\lib\site-packages\sklearn\utils\validation.py", line 433, in check_array
    array = np.array(array, dtype=dtype, order=order, copy=copy)
ValueError: could not convert string to float: '39,6,77516,1,13,3,9,4,1,2,2174,0,40,1'

Thanks for all the help.

**Comment by Baukebrenninkmeijer** [comment]
That is the same error as @TrinhDinhPhuc had. You need to use a semicolon as separator or change the line mentioned above to accept data with commas as separator.

**Comment by TrinhDinhPhuc** [comment]
I used your fork repo. I sill got this error
Traceback (most recent call last):
File "main.py", line 179, in 
tf.app.run()
File "C:\Anaconda\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run _sys.exit(main(argv))
File "main.py", line 158, in main
tablegan.train(FLAGS)
TypeError: train() missing 1 required positional argument: 'experiment'

How to fix this?

I read your comment but i dont understand what `comet_ml` is

**Comment by Baukebrenninkmeijer** [comment]
@TrinhDinhPhuc Are you on the most recent version of the repo? Cause this error shouldn't happen there anymore. Comet ML is this: https://comet.ml. You can send metrics and stuff and it will automatically plot stuff. However, it's not required to run this and there should be no traces left of it in the most recent push.

**Comment by Baukebrenninkmeijer** [comment]
To check, you cloned this: https://github.com/Baukebrenninkmeijer/tableGAN and not the current repository?

**Comment by TrinhDinhPhuc** [comment]
Oh thanks @Baukebrenninkmeijer 

There is an error (`Load failed...`)something I dont understand, here is the log
```
Start Training...

 [*] Reading checkpoints from checkpoint/Adult/OI_11_00 ...
checkpoint dir: checkpoint/Adult/OI_11_00
None
 [*] Failed to find a checkpoint
 [!] Load failed...
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 0] [   0/   4] time: 1.4975, d_loss: 1.39496779, g_loss: 1.22490883, c_loss: 0.72457600
 [Saving checkpoints in checkpoint/Adult/OI_11_00/Adult_500_7_7 ...
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 0] [   1/   4] time: 1.7048, d_loss: 1.38959050, g_loss: 1.28255391, c_loss: 0.66120583
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 0] [   2/   4] time: 1.8123, d_loss: 1.38913262, g_loss: 1.31098974, c_loss: 0.60391492
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 1] [   0/   4] time: 1.9177, d_loss: 1.39072633, g_loss: 1.32258177, c_loss: 0.55135280
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 1] [   1/   4] time: 2.0205, d_loss: 1.39046645, g_loss: 1.32317853, c_loss: 0.50505811
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 1] [   2/   4] time: 2.1233, d_loss: 1.38874364, g_loss: 1.31484282, c_loss: 0.46205667
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 2] [   0/   4] time: 2.2357, d_loss: 1.38782644, g_loss: 1.29291487, c_loss: 0.42293963
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 2] [   1/   4] time: 2.3389, d_loss: 1.38637507, g_loss: 1.27342105, c_loss: 0.38857025
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 2] [   2/   4] time: 2.4403, d_loss: 1.38671589, g_loss: 1.25579309, c_loss: 0.35618657
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 3] [   0/   4] time: 2.5462, d_loss: 1.38731885, g_loss: 1.24947357, c_loss: 0.33117515
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 3] [   1/   4] time: 2.6488, d_loss: 1.38659251, g_loss: 1.26212239, c_loss: 0.30301544
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 3] [   2/   4] time: 2.7529, d_loss: 1.38599324, g_loss: 1.27494025, c_loss: 0.27863643
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 4] [   0/   4] time: 2.8594, d_loss: 1.38886619, g_loss: 1.27736783, c_loss: 0.25769889
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 4] [   1/   4] time: 2.9643, d_loss: 1.39175844, g_loss: 1.26607990, c_loss: 0.24142206
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 4] [   2/   4] time: 3.0680, d_loss: 1.39207304, g_loss: 1.27437115, c_loss: 0.22352202
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 5] [   0/   4] time: 3.1772, d_loss: 1.39092803, g_loss: 1.28803706, c_loss: 0.20751849
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 5] [   1/   4] time: 3.2793, d_loss: 1.39146876, g_loss: 1.28614902, c_loss: 0.19421048
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 5] [   2/   4] time: 3.3852, d_loss: 1.39231396, g_loss: 1.30943596, c_loss: 0.18280661
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 6] [   0/   4] time: 3.4917, d_loss: 1.39429712, g_loss: 1.34158540, c_loss: 0.17202589
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 6] [   1/   4] time: 3.5957, d_loss: 1.39460921, g_loss: 1.36735201, c_loss: 0.16109954
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 6] [   2/   4] time: 3.6976, d_loss: 1.39346647, g_loss: 1.38980103, c_loss: 0.15224275
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 7] [   0/   4] time: 3.8083, d_loss: 1.39062941, g_loss: 1.40843511, c_loss: 0.14188115
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 7] [   1/   4] time: 3.9110, d_loss: 1.38859248, g_loss: 1.42068398, c_loss: 0.13548662
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 7] [   2/   4] time: 4.0178, d_loss: 1.38632095, g_loss: 1.42030931, c_loss: 0.12917124
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 8] [   0/   4] time: 4.1264, d_loss: 1.38400245, g_loss: 1.41657090, c_loss: 0.12014424
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 8] [   1/   4] time: 4.2322, d_loss: 1.38075840, g_loss: 1.43280172, c_loss: 0.11510154
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 8] [   2/   4] time: 4.3355, d_loss: 1.38133669, g_loss: 1.43915009, c_loss: 0.10810666
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 9] [   0/   4] time: 4.4432, d_loss: 1.38597298, g_loss: 1.41633081, c_loss: 0.10254587
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 9] [   1/   4] time: 4.5499, d_loss: 1.38926446, g_loss: 1.39482594, c_loss: 0.09804408
Dataset: [Adult] -> [OI_11_00] -> Epoch: [ 9] [   2/   4] time: 4.6553, d_loss: 1.39068675, g_loss: 1.38106096, c_loss: 0.09351491
```

**Comment by Baukebrenninkmeijer** [comment]
Yeah, this is because this is the first time you're training, so there is no checkpoint yet. This system loads checkpoints of previous training runs as to continue training where the previous run left off. However, since this isn't used that often anymore I changed it to create a new checkpoint every run. When generating data with their proposed cli command, it will use the latest checkpoint it can find for that dataset.

**Comment by soft-nougat** [comment]
Again - thanks so much Bauke!

It's working now! The Adult dataset workflow fix:
1) Download Bauke's repo - https://github.com/Baukebrenninkmeijer/tableGAN;
2) Change the names of the datasets in .../data/adult to Adult and Adult_labels;
3) Go to model.py and change: 
Line 816 to X = pd.read_csv(self.train_data_path + ".csv", sep=',')
4) Open utils.py and change:
Line 405 to  origin_data = pd.read_csv(origin_data_path + ".csv", sep=',')
Line 432 to rsf_out.to_csv(f'{save_dir}/{config.dataset}_{config.test_id}_fake.csv' , index=False, sep=',')
5)Open cmd in the folder where you extracted all the files
6) Run python main.py --dataset=Adult --test_id=OI_11_00 --train
- Checkpoints created
7) Run python main.py --dataset=Adult --test_id=OI_11_00 
8) Generated data is in samples/adult/

;)

**Comment by TrinhDinhPhuc** [comment]
Yes That's right @soft-nougat . Thank you Bauke! 
I have another question, @soft-nougat @Baukebrenninkmeijer @mahmoodm2 lets discuss together :D. I will open a new issue. So you should close this issue.

**Comment by Baukebrenninkmeijer** [comment]
@soft-nougat @TrinhDinhPhuc You're welcome. You can close the issues yourself btw.

**Comment by TrinhDinhPhuc** [comment]
Oh thanks @Baukebrenninkmeijer 
Have a good one :)
